name: Latest Bad Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print on console
        run: echo Hello GH Actions!
        
      - name: Print a few lines
        run: |
          echo First line!
          echo Second line!

      - name: Print title
        run: echo "${{ github.event.issue.title }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run HelloNY Python script
        run: |
          python ./HelloNY.py
